### ISSUE TITLE
rand_bracket_seq有bug

### ISSUE THREAD

**Issue by ChuTian-SCPC** [bandiaoz/generator#1]
可以试一下`std::string s = rand_bracket_seq(5, 10);`，我是会报错`call of overloaded 'rand_bracket_seq(int, int)' is ambiguous`。

**Comment by bandiaoz** [comment]
确实是会匹配到`std::string rand_bracket_seq(int from, int to, std::string brackets = "()")`和`std::string rand_bracket_seq(int from, int to, const char* format = "()", ...)`两个函数。目前一个方案是不要默认参数，额外写两个不带 `brackets` 的函数。
另外如果不实现`std::string rand_bracket_seq(int from, int to, const char* format = "()", ...)`这个函数，也是不会有冲突的，它的功能似乎也可以被`std::format()` 替代。请问这么设计是出于兼容低版本cpp的考虑还是其他原因，包括其他使用`format`的地方，例如`long long rand_int(const char* format, ...)`。
非常感谢你的关注！

**Comment by ChuTian-SCPC** [comment]
我原本的方案是对`std::string rand_bracket_seq(int from, int to, const char* format = "()", ...)`不设默认参数，不过你的方案看起来更好。
`generator`本身实现中就有很多局限于C++11版本的设计。比如`std::filesystem`可以更好的处理文件，`requires`可以取代`SFINAE`。对于字符串相关的函数用`std::string`和`const char*,...`两个的情况也基于此，`std::format`是C++20，还是比较新的版本中才有的特性。
