### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by ChuTian-SCPC** [bandiaoz/generator#2]
1. 函数`unsigned long long __string_to_value`中用的函数错了。
应该是:
```cpp
template<>
unsigned long long __string_to_value(const std::string& s) {
    if (__is_real_format(s)) 
        return (unsigned long long)__string_to_value<double>(s);
    return std::stoull(s);
}
```
2. `ConvexHull`的函数`__check_limit`中的信息应该用`invaild`。
3. 测试中`tree.set_swap_node(false); // 设置是否随机交换 fa, u，默认为有根树交换，无根树不交换，注意不要在无根树下设置为交换`描述有问题。
默认是有根树为不交换，无根树交换。
交换会随机`u v`或者`v u`，这对于无根树的输出是一个比较常见的形式。
设置它的思路在于，对于有根树，它既可以在明确根的情况下也以边可以交换的形式输出，也可以支持`father son`这样的形式输出。并且如果需要一些不常见的形式，也可以利用它，比如：输出一行 $n$ 个数表示该结点的父亲，如果它是根节点，则为 $-1$ 。
```cpp
#include<bits/stdc++.h>
#include"generator.h"
using namespace std;
using namespace generator::all;

int main() {
    init_gen();
    unweight::Tree tree(10, 1);
    tree.set_is_rooted(true);
    tree.set_root(5);
    tree.gen();
    vector<int> f(11, -1);
    for (auto edge : tree.edges()) f[edge.v()] = edge.u();
    for (int i = 1; i <= 10; i++) cout<<f[i]<<" ";
    cout<<endl;
    return 0;
}

```

**Comment by bandiaoz** [comment]
感谢指出，另外应该是 invalid 而不是 invaild，类似地，可以搜一下 `generator.h` 中的 pleace、gengrator、accuarcy、Vaild、negtive、becase、beign、cloumn、vaild 等。

**Comment by ChuTian-SCPC** [comment]
感谢提醒！欢迎您给generator提出pr/issue。
